# Generated by Django 5.0 on 2023-12-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_customer_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('time_log', models.TimeField(help_text='Enter the exact time!')),
            ],
        ),
        migrations.RenameField(
            model_name='person',
            old_name='phone',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
    ]
