# Generated by Django 5.0 on 2023-12-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_logger_rename_phone_person_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='customer',
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='prices',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='cuisine',
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
